#docker-compose.yml
version: '3.7'

services:
  api:
    build: ./app
    container_name: "api"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000

  web:
    build: ./web
    container_name: "web"
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - 4242:4242